language: bash

addons:
  apt:
    packages:
      - fakeroot

before_script:
  - sudo apt-key adv --keyserver keys.gnupg.net --recv-keys 9E3E53F19C7DE460
  - echo "deb http://repo.aptly.info/ squeeze main" | sudo tee -a /etc/apt/sources.list.d/aptly.list > /dev/null
  - sudo apt-get update -qq
  - sudo apt-get install aptly -qq -y

script:
  - ./make_repo_plexmediaserver.sh
